# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'samleeney/tmux-agent-status'


setw -g aggressive-resize on
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
set -g default-terminal "screen-256color"
set-option -g history-limit 1000000000
set-option -g mouse on
set-option -g default-shell "/bin/bash"
set-option -g default-command bash

set -g @mighty-scroll-show-indicator on

# Unset env vars in case a direnv-managed folder was entered before starting tmux
# https://github.com/direnv/direnv/wiki/Tmux
#set-option -g update-environment "DIRENV_DIFF DIRENV_DIR DIRENV_WATCHES"
#set-environment -gu DIRENV_DIFF
#set-environment -gu DIRENV_DIR
#set-environment -gu DIRENV_WATCHES
#set-environment -gu DIRENV_LAYOUT

# sessionx settings: https://github.com/omerxx/tmux-sessionx
set -g @sessionx-bind 'o'
set -g @sessionx-ls-command 'lsd --tree --color=always --icon=always'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-git-branch 'on'
set -g @sessionx-custom-paths '~/p/w,~/p'

# claude-tmux https://github.com/nielsgroen/claude-tmux
# bind-key C-b display-popup -E -w 80 -h 30 "~/.cargo/bin/claude-tmux"
set -g @agent-park-key "P"
set -g @agent-switcher-style "both"
set -g @agent-status-display-method "popup"

bind p previous-window
bind n next-window

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'
