#!/usr/bin/env bash
# shellcheck disable=SC2154
BASH_ALIASES_DIR="${XDG_CONFIG_HOME}/bash/bash_aliases.d"
if [[ -d "${BASH_ALIASES_DIR}" ]]; then
    for file in "${BASH_ALIASES_DIR}"/*.sh; do
        if [[ -r "${file}" ]]; then
            # shellcheck disable=SC1090
            . "${file}"
        fi
    done
    unset file
fi
