[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.status]
show_tools = true
show_env = true

[tools]
age = "latest"
node = "latest"
python = "3.13"
sops = "latest"
usage = "latest"
uv = "latest"

[env]
_.file = "${HOME}/.config/mise/.env.json"
SOPS_AGE_KEY_FILE = "${HOME}/.config/chezmoi/age.txt"
SOPS_AGE_RECIPIENTS = "age17lav4s6j0lchx0t05mr85l3htuqk7eeuth5ksvwzv0c8dw63zc4stw50nf"
PVECONTROL_CLUSTER = "s"
